services:
  # JAZZY
  jazzy-mac:
    container_name: jazzy-mac
    image: gai313/nakalab_docker:jazzy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}

  jazzy-vnc:
    container_name: jazzy-vnc
    image: gai313/nakalab_docker:jazzy-vnc
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./vnc/Dockerfile.jazzy.vnc
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
    ports:
      - 5901:5901

  # HUMBLE
  humble-mac:
    container_name: humble-mac
    image: gai313/nakalab_docker:humble-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}

  # FOXY
  foxy-mac:
    container_name: foxy-mac
    image: gai313/nakalab_docker:foxy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}

  # NOETIC
  noetic-mac:
    container_name: noetic-mac
    image: gai313/nakalab_docker:noetic-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
    command: /bin/bash -c ". /opt/ros/noetic/setup.bash && roscore"
