services:
  # JAZZY
  jazzy-mac:
    container_name: jazzy-mac
    image: gai313/nakalab_docker:jazzy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}

  jazzy-gpu:
    container_name: jazzy-gpu
    image: gai313/nakalab_docker:jazzy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  jazzy-vnc:
    container_name: jazzy-vnc
    image: gai313/nakalab_docker:jazzy-vnc
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./vnc/Dockerfile.jazzy.vnc
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
    ports:
      - 5901:5901

  # IRON
  iron-mac:
    container_name: iron-mac
    image: gai313/nakalab_docker:iron-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
  
  iron-gpu:
    container_name: iron-gpu
    image: gai313/nakalab_docker:iron-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"
    
  # HUMBLE
  humble-mac:
    container_name: humble-mac
    image: gai313/nakalab_docker:humble-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
  
  humble-gpu:
    container_name: humble-gpu
    image: gai313/nakalab_docker:humble-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  # FOXY
  foxy-mac:
    container_name: foxy-mac
    image: gai313/nakalab_docker:foxy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
  
  foxy-gpu:
    container_name: foxy-gpu
    image: gai313/nakalab_docker:foxy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  # NOETIC
  noetic-mac:
    container_name: noetic-mac
    image: gai313/nakalab_docker:noetic-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
    command: /bin/bash -c ". /opt/ros/noetic/setup.bash && roscore"
  
  noetic-gpu:
    container_name: noetic-gpu
    image: gai313/nakalab_docker:noetic-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: " /opt/ros/noetic/setup.bash && roscore & terminator"
