services:
  # JAZZY
  jazzy-mac:
    container_name: jazzy-mac
    image: gai313/nakalab_docker:jazzy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - mac
    command: "/bin/bash -c terminator"


  jazzy-cpu:
    container_name: jazzy-cpu
    image: gai313/nakalab_docker:jazzy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    command: "/bin/bash -c terminator"

  jazzy-gpu:
    container_name: jazzy-gpu
    image: gai313/nakalab_docker:jazzy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  jazzy-vnc:
    container_name: jazzy-vnc
    image: gai313/nakalab_docker:jazzy-vnc
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=${ROS_AUTOMATIC_DISCOVERY_RANGE}
    ports:
      - 6080:80
    profiles:
      - debug

  # IRON
  iron-mac:
    container_name: iron-mac
    image: gai313/nakalab_docker:iron-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - mac
  
  iron-cpu:
    container_name: iron-cpu
    image: gai313/nakalab_docker:iron-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    command: "/bin/bash -c terminator"

  iron-gpu:
    container_name: iron-gpu
    image: gai313/nakalab_docker:iron-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  iron-vnc:
    container_name: iron-vnc
    image: gai313/nakalab_docker:iron-vnc
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    ports:
      - 6080:80
    profiles:
      - debug
  
  # HUMBLE
  humble-mac:
    container_name: humble-mac
    image: gai313/nakalab_docker:humble-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - mac

  humble-cpu:
    container_name: humble-cpu
    image: gai313/nakalab_docker:humble-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    command: "/bin/bash -c terminator"
    
  humble-gpu:
    container_name: humble-gpu
    image: gai313/nakalab_docker:humble-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  humble-vnc:
    container_name: humble-vnc
    image: gai313/nakalab_docker:humble-vnc
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    ports:
      - 6080:80
    profiles:
      - debug
      
  # FOXY
  foxy-mac:
    container_name: foxy-mac
    image: gai313/nakalab_docker:foxy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - mac
  
  foxy-cpu:
    container_name: foxy-cpu
    image: gai313/nakalab_docker:foxy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    command: "/bin/bash -c terminator"

  foxy-gpu:
    container_name: foxy-gpu
    image: gai313/nakalab_docker:foxy-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "/bin/bash -c terminator"

  foxy-vnc:
    container_name: foxy-vnc
    image: gai313/nakalab_docker:foxy-vnc
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    ports:
      - 6080:80
    profiles:
      - debug
      
  # NOETIC
  noetic-mac:
    container_name: noetic-mac
    image: gai313/nakalab_docker:noetic-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash -c ". /opt/ros/noetic/setup.bash && roscore & terminator"
    profiles:
      - mac
  
  noetic-cpu:
    container_name: noetic-cpu
    image: gai313/nakalab_docker:noetic-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    command: /bin/bash -c ". /opt/ros/noetic/setup.bash && roscore & terminator"

  noetic-gpu:
    container_name: noetic-gpu
    image: gai313/nakalab_docker:noetic-base
    privileged: true
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash -c ". /opt/ros/noetic/setup.bash && roscore & terminator"

  noetic-vnc:
    container_name: noetic-vnc
    image: gai313/nakalab_docker:noetic-vnc
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
    ports:
      - 6080:80
    profiles:
      - debug
