ARG DISTRO=jazzy
FROM gai313/nakalab_docker:${DISTRO}-base

RUN if [ "${DISTRO}" = "jazzy" ]; then \
        pip install --break-system-packages notebook; \
    else \
        pip install notebook; \
fi

CMD ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''"]
